[package]
name = "actix-web-lua-server"
version = "0.1.0"
authors = ["Poga Po <poga.bahamut@gmail.com>"]

[dependencies]
actix = "0.9"
actix-web = "2"
env_logger = "0.5.12"
futures = "0.3"

actix-lua = { path = "../.." }